spring.application.name=autoflexspring

spring.datasource.url=jdbc:postgresql://localhost:5432/autoflex_test_db
spring.datasource.username=admin
spring.datasource.password=psswrd_autoflex

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always