INSERT INTO input (name, in_stock) VALUES ('Wood Plank', 100) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Iron Nail', 80) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Iron Ingot', 50) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Leather Strip', 200) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Gemstone', 30) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Cloth', 150) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Steel Ingot', 80) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Glass Shard', 60) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Bone Fragment', 120) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Magic Essence', 40) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Copper Wire', 90) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Silver Nugget', 70) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Gold Coin', 200) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Clay', 110) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Paper', 300) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Ink', 80) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Feather', 150) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('String', 200) ON CONFLICT DO NOTHING;
INSERT INTO input (name, in_stock) VALUES ('Flint', 100) ON CONFLICT DO NOTHING;

INSERT INTO product (name, price) VALUES ('Wooden Sword', 10) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Iron Shield', 25) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Leather Armor', 15) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Gemstone Ring', 50) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Cloth Robe', 20) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Steel Helmet', 30) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Glass Bottle', 5) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Bone Dagger', 12) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Magic Wand', 40) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Copper Bracelet', 8) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Silver Necklace', 35) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Gold Ring', 60) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Clay Pot', 7) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Paper Scroll', 3) ON CONFLICT DO NOTHING;
INSERT INTO product (name, price) VALUES ('Ink Bottle', 4) ON CONFLICT DO NOTHING;

INSERT INTO product_input (product_id, input_id, input_needed) VALUES (1, 1, 5) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (1, 2, 10) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (2, 2, 10) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (2, 3, 5) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (3, 3, 15) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (4, 4, 2) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (5, 5, 20) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (6, 6, 8) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (7, 7, 3) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (8, 8, 10) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (9, 9, 5) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (10, 10, 12) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (11, 11, 7) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (12, 12, 4) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (13, 13, 6) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (14, 14, 10) ON CONFLICT DO NOTHING;
INSERT INTO product_input (product_id, input_id, input_needed) VALUES (15, 15, 5) ON CONFLICT DO NOTHING;